version: '2'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  login-service:
    build: ./login-service
    container_name: 'login-service'
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3000:3000
    command: [ 'start']

  api-service:
    build: ./api-service
    container_name: 'api-service'
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3001:3001
    command: [ 'start']
